/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/95hdHePSfHV
 */
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { useState, type Dispatch, type SetStateAction, type ChangeEvent, useEffect } from "react"

export type Filter = {
  name: string;
  subfilters: string[];
}

export function FiltersMenu({
  filters,
  setSelectedFilters
}: { 
  filters: Filter[],
  setSelectedFilters: Dispatch<SetStateAction<string[]>>
}) {
  const [selectedCheckboxes, setSelectedCheckboxes] = useState<string[]>([])

  const handleCheckedChange = (e: ChangeEvent<HTMLInputElement>) => {
    const name = e.target.name

    if (e.target.checked) {
      setSelectedCheckboxes([...selectedCheckboxes, name])
    } else {
      setSelectedCheckboxes(selectedCheckboxes.filter((checkbox) => checkbox !== name))
    }
  }

  useEffect(() => {
    setSelectedFilters(selectedCheckboxes)
  }, [selectedCheckboxes])

  return (
    <aside className="bg-white p-4 w-full md:w-[300px]">
      <Card className="mb-6">
        <CardHeader className="font-semibold text-lg">Filters</CardHeader>
        <CardContent>
          <div className="flex flex-col gap-4">
            {filters.map((filter) => (
              <details key={filter.name}>
                <summary className="font-semibold mb-2 text-sm">{filter.name.toUpperCase()}</summary>
                <div className="grid gap-2 pl-4">
                  {filter.subfilters.map((subfilter) => (
                    <Label key={subfilter} className="flex items-center gap-2 font-normal">
                      <input type="checkbox" name={`${filter.name}:${subfilter}`} id={`${filter}:${subfilter}`} onChange={handleCheckedChange} />
                      {subfilter}
                    </Label>
                  ))}
                  {/* <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="category-books" />
                    Books
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="category-electronics" />
                    Electronics
                  </Label>
                  <Label className="flex items-center gap-2 font-normal">
                    <Checkbox id="category-fashion" />
                    Fashion
                  </Label> */}
                </div>
              </details>
            ))}
            {/* <details>
              <summary className="font-semibold mb-2 text-sm">category</summary>
              <div className="grid gap-2 pl-4">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="category-books" />
                  Books
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="category-electronics" />
                  Electronics
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="category-fashion" />
                  Fashion
                </Label>
              </div>
            </details>
            <details>
              <summary className="font-semibold mb-2 text-sm">Price Range</summary>
              <div className="grid gap-2 pl-4">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="price-under-50" />
                  Under $50
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="price-50-100" />
                  $50 - $100
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="price-100-200" />
                  $100 - $200
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="price-200-plus" />
                  $200 and above
                </Label>
              </div>
            </details>
            <details>
              <summary className="font-semibold mb-2 text-sm">Seller Rating</summary>
              <div className="grid gap-2 pl-4">
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="rating-5" />
                  5 stars
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="rating-4" />
                  4 stars & above
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="rating-3" />
                  3 stars & above
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="rating-2" />
                  2 stars & above
                </Label>
                <Label className="flex items-center gap-2 font-normal">
                  <Checkbox id="rating-1" />
                  1 star & above
                </Label>
              </div>
            </details> */}
            <Button className="mt-4" variant="default">
              Apply Filters
            </Button>
          </div>
        </CardContent>
      </Card>
    </aside>
  )
}
